In [ ]:
import pandas as pd

df = pd.DataFrame(columns = ["a", "b", "c"], data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(df)
print(len(df))
print(df.index)

In [5]:
a = "abc"
a[0:1]
b = a[0:1]
print(a)

abc


In [2]:
for x in [1,2,3,4,5]:
    a = x
    
print(a)
print(x)

5
5


In [3]:
a=b = 10
print(a)
a=30
print(b)

10
10


In [3]:
import numpy as np
x = [2, 4, 6, 8, 10]
x = (x + np.roll(x, -1))[:-1] / 2.0
print(x)

[3. 5. 7. 9.]


In [6]:
import numpy as np
def get_center_of_bin_edges(bin_edges):
    bin_centers = []
    
    for x in np.arange(start=0, stop=len(bin_edges)-1, step=1):
        bin_centers.append((bin_edges[x] + bin_edges[x + 1]) / 2.0)
        
    return bin_centers

print(get_center_of_bin_edges([1,2,3,4,5]))


[1.5, 2.5, 3.5, 4.5]


In [7]:
generated_data = np.empty(shape = (0, 0))
generated_data = np.append(generated_data, [1,2,3])

a = np.array([1,2,3])

print(generated_data)
print(a)

[1. 2. 3.]
[1 2 3]


In [10]:
def generate_data(repetition_list, data_range_list):
    generated_data = np.empty(shape=(0, 0))
    for index, value in enumerate(repetition_list):
        generated_data = np.append(generated_data, np.linspace(start=data_range_list[index][0], stop=data_range_list[index][0]+1, num=value))
    return generated_data

print(generate_data([10], [[1,5]]))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
